name: "Close Stale Issues"
on: [issues]

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v3.0.11
    
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue is labelled as stale because it has been open for more than 7 days with no activity.'
        days-before-stale: 7
        days-before-close: -1
        stale-issue-label: 'Stale'
        exempt-issue-labels: 'Assigned,Announcement,Pinned'
        remove-stale-when-updated: true
        
